### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by sasquatch7816** [yianL/atom-spotified#9] opened 2016-11-07 16:59 UTC
Cannot install. Tried closing atom and retrying but won't install. Click the button and install animation appears, but then disappears and is replaced with install button again. No error thrown about a problem installing.

**Comment by FlorianWendelborn** [comment] 2016-11-07 17:35
@sasquatch7816 Can you install other packages? What's your macOS and atom version?

**Comment by sasquatch7816** [comment] 2016-11-07 17:37
I can install others and I'm on Windows 10, atom version 1.11.2

**Comment by FlorianWendelborn** [comment] 2016-11-07 20:43
> Only OSX is supported at this moment since I'm using AppleScript to interact with Spotify.

\- `README.md`

I guess you can close this issue then, as this is currently the expected behavior. Would be great if Windows could be supported, but unfortunately it isn't right now.

The reason why is because Windows (for obvious reasons) does not support AppleScript.

@yianL Is there anything we can do to show a warning or error when a user attempts to install on the wrong OS?

**Comment by sasquatch7816** [comment] 2016-11-07 21:02
Might want to make it a little more clear!

**Comment by yianL** [comment] 2016-11-07 21:41
@dodekeract You are right. This plugin relies on Spotify's AppleScript api to get information about the player and track, so it wouldn't work on Windows/Linux machines at the moment. I'd be more than happy to support them if I can find a way to access the information on those platforms, but I just haven't had the time to dig too deep into it.

As for adding a warning message, I can certainly do something to surface the restriction better. If you guys have any ideas, let me know too!

**Comment by FlorianWendelborn** [comment] 2016-11-08 01:07
@yianL as a start, you might want to put this emoji next to the "only works on macOS" notice:
:warning: `:warning:`

That greatly improves visual grepping.

Regarding @sasquatch7816, it's literally the 4th sentence in the README. Of course it **can** be improved, but I don't think it's unclear right now.

**Comment by yianL** [comment] 2016-11-08 23:00
Thanks for the suggestion. README file updated.

**Closed as completed** 2017-05-18 04:16 UTC
